org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=384m -XX:HeapBaseMinAddress=4g -Dfile.encoding=UTF-8

android.useAndroidX=true

org.gradle.caching=true
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.daemon=false

# Fix for cross-drive Kotlin incremental compilation error on Windows
# (pub cache on C: drive, project on D: drive)
kotlin.incremental=false

# Bypass strict JVM target consistency checks (fixes plugins like in_app_review)
kotlin.jvm.target.validation.mode=warning
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
